name: Deploy Shortcode

on:
  push:
    branches: [main, stage, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Building the app

  #deploy em desenvolvimento
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{vars.URL}}
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Shortcode Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "."
          REMOTE_HOST: ${{secrets.SSH_HOST}}
          REMOTE_USER: ${{secrets.SSH_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          TARGET: "/var/www/shortcodeDev"

  #deploy em stage
  deploy-stage:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{vars.URL}}
    needs: deploy-development
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Shortcode Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "."
          REMOTE_HOST: ${{secrets.SSH_HOST}}
          REMOTE_USER: ${{secrets.SSH_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          TARGET: "/var/www/shortcodeStage"

  #deploy em production
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{vars.URL}}
    needs: deploy-stage
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Shortcode Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "."
          REMOTE_HOST: ${{secrets.SSH_HOST}}
          REMOTE_USER: ${{secrets.SSH_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          TARGET: "/var/www/shortcode"
